<?php	if ( ! defined('BASEPATH')) exit('No dirct script access allowed');

class Trader_contract {
	var $tc = 'trader_contract';
	var $tc_1 = 'id';
	var $tc_2 = 'name';
	var $tc_3 = 'trader_code';
	var $tc_4 = 'bill_kind_code';
	var $tc_5 = 'age';
	var $tc_6 = 'begin';
	var $tc_7 = 'end';
	var $tc_8 = 'publish_kind';
	var $tc_9 = 'publish_day';
	var $tc_10 = 'publish_week';
	var $tc_11 = 'publish_month';
	var $tc_12 = 'publish_season_month';
	var $tc_13 = 'enter_kind';
	var $tc_14 = 'enter_day';
	var $tc_15 = 'enter_week';
	var $tc_16 = 'enter_month';
	var $tc_17 = 'enter_season_month';
	var $tc_18 = 'collection_kind';
	var $tc_19 = 'collection_day';
	var $tc_20 = 'collection_week';
	var $tc_21 = 'collection_month';
	var $tc_22 = 'collection_season_month';
	var $tc_23 = 'bill_price_kind';
	var $tc_24 = 'month_rent_price';
	var $tc_25 = 'entity_price';
	var $tc_26 = 'action_price';
	var $tc_27 = 'send_condition';
	var $tc_28 = 'send_condition_times';
	var $tc_29 = 'contract_remark';
	var $tc_30 = 'email_send';
	var $tc_31 = 'email_publish_kind';
	var $tc_32 = 'email_publish_day';
	var $tc_33 = 'email_publish_week';
	var $tc_34 = 'email_publish_month';
	var $tc_35 = 'email_publish_season_month';
	var $tc_36 = 'ftp_ip';
	var $tc_37 = 'ftp_account';
	var $tc_38 = 'ftp_password';
	var $tc_39 = 'ftp_path';
	var $tc_40 = 'ftp_receive_path';
	var $tc_41 = 'create_user';
	var $tc_42 = 'create_time';
	var $tc_43 = 'update_user';
	var $tc_44 = 'update_time';
	
}